gems:
  - jekyll-redirect-from
  - jemoji
  - jekyll-relative-links

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

relative_links:
  enabled:     true
  collections: true

topnav_title: Hygieia Executive
# this appears on the top navigation bar next to the home button

site_title: Hygieia
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Capital One
# this appears in the footer

github_editme_path: 
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

#disqus_shortname: cap1devops
disqus_shortname:
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
# these are the files and directories that jekyll will exclude from the build

feedback_subject_line: Hygieia

feedback_email: hygieia@capitalone.com
# used as a contact email for the Feedback link in the top navigation bar

#feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

#feedback_text: "Feedback"
# if you uncomment the previous line, it changes the Feedback text

#feedback_link: "https://gitter.im/capitalone/Hygieia"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
  tooltips:
    output: true
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: hygieia_sidebar
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: hygieia_sidebar

# these are defaults used for the frontmatter for these file types

sidebars:
- hygieia_sidebar

description: "Intended as a documentation theme based on Jekyll for technical writers documenting software and other technical products, this theme has all the elements you would need to handle multiple products with both multi-level sidebar navigation, tags, and other documentation features."
# the description is used in the feed.xml file

# needed for sitemap.xml file only
url: http://idratherbewriting.com
