export class Vast {
    vastID:string
    vastApplID:string
    vastAppType:string
    vastAppName:string
    vastAcronym:string
    vastInvestmentStatus:string
    vastAvailabilityStatus:string
    vastBusinessUnit:string
    vastRoadMapIndicator:string
    vastStatus:string
    vastCustodianContactName:string
    vastCustodianContactEmail:string
    vastCustodianContactEid:string
    vastTierOneContactName:string
    vastTierOneContactEmail:string
    vastTierOneContactEid:string
    vastTierOneContactTitle:string
    vastTierTwoContactName:string
    vastTierTwoContactEmail:string
    vastTierTwoContactEid:string
    vastTierTwoContactTitle:string
    vastTierThreeContactName:string
    vastTierThreeContactEmail:string
    vastTierThreeContactEid:string
    vastTierThreeContactTitle:string
    vastTierFourContactName:string
    vastTierFourContactEmail:string
    vastTierFourContactEid:string
    vastTierFourContactTitle:string
    vastTierFiveContactName:string
    vastTierFiveContactEmail:string
    vastTierFiveContactEid:string
    vastTierFiveContactTitle:string
    vastTierSixContactName:string
    vastTierSixContactEmail:string
    vastTierSixContactEid:string
    vastTierSixContactTitle:string
    vastTierSevenContactName:string
    vastTierSevenContactEmail:string
    vastTierSevenContactEid:string
    vastTierSevenContactTitle:string
    updatedTimeStamp:number
    isIT:boolean
}